apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  annotations:
    prometheus.io/store: "store1"
    prometheus.io/annotations: ".*"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: hello-world:latest
          ports:
            - containerPort: 8080
